### ISSUE TITLE
[SUGGESTION] Relationships

### ISSUE THREAD

**Issue by macMikey** [trevordevore/sql-yoga#1]
Change
one-to-one
one-to-many
many-to-many

to either
1-1
1-n
n-n

or
1:1
1:n
n:n

or
1
1n
nn

**Comment by trevordevore** [comment]
I like that idea. Check out this PR: https://github.com/trevordevore/sql-yoga/pull/2

The changes are on the `tkd-short-relationship-names` branch.

**Comment by macMikey** [comment]
Looks good.
